#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Sep 10 12:01:09 CEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 55c9f3813b2342b8b7e66549125deb3d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot top_block_tb_behav xil_defaultlib.top_block_tb -log elaborate.log"
xelab -wto 55c9f3813b2342b8b7e66549125deb3d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot top_block_tb_behav xil_defaultlib.top_block_tb -log elaborate.log

