#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 10 12:01:16 CEST 2020
# SW Build 2552052 on Fri May 24 14:47:09 MDT 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim top_block_tb_behav -key {Behavioral:sim_1:Functional:top_block_tb} -tclbatch top_block_tb.tcl -view /home/bjorn/Desktop/Lekekasse/Array_Sorting/selection_sort_hw/top_block_tb_behav.wcfg -log simulate.log"
xsim top_block_tb_behav -key {Behavioral:sim_1:Functional:top_block_tb} -tclbatch top_block_tb.tcl -view /home/bjorn/Desktop/Lekekasse/Array_Sorting/selection_sort_hw/top_block_tb_behav.wcfg -log simulate.log

